source 'https://rubygems.org'
ruby '2.1.2'
gem 'rails', '4.1.1'
 # Rails defaults
#gem 'arel' '5.0.1.20140414130214'
#gem 'builder' '3.2.2'
gem 'sqlite3'
gem 'sass-rails', '~> 4.0.3'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder'
#gem 'hike' '2.1.3'
 # learn-rails
gem 'activerecord-tableless'
gem 'compass-rails', '~> 1.1.7'
gem 'figaro', '~>1.0.0.rc1'
gem 'gibbon'
gem 'google_drive'
gem 'high_voltage'
gem 'simple_form'
gem 'zurb-foundation'
gem 'sass', '3.2.19'
group :development do
gem 'better_errors'
gem 'quiet_assets'
gem 'rails_layout'
end
