# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 638f212db2ce1fee217b6693672ac9cb0fcd0834b1976c7432abedd3e5acd01f15971f80702363055fca0d989ea955a9f76355bd8895e0c79df29b83a3bb28fa

test:
  secret_key_base: 3cb041d75c7326cfceb4eb121030de4d9b61e315787563d1d218c11ec045002a446a2407894e8364e38fee2157dca7f5249e22b1328291d2e156ed6bdc36e9c8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
